#ifndef SETTINGS_H_INCLUDED
#define SETTINGS_H_INCLUDED

#define APP_NAME "EVOC2D"
#define FULLSCREEN true
#define DEFAULT_SCRN_WIDTH 2000
#define DEFAULT_SCRN_HEIGHT 1500
#define INITIAL_CREATURE_COUNT 70
#define FOOD_COUNT 300
#define FOOD_RADIUS 6000
#define FOOD_COOLDOWN 24
#define VAO_POOL_VBO_CAPACITY 20000
#define VAO_POOL_EBO_CAPACITY 20000
#define COMPONENT_RADIUS 0.1f
#define MAX_CHILDREN 7
#define GROWTH_RADIUS 0.50f
#define GROWTH_ANGLE 2.0f * M_PI / MAX_CHILDREN
#define CREATURE_SPAWN_RADIUS 5000
#define STRUCTURAL_MUTATION_CHANCE 0.35f
#endif
