#ifndef SETTINGS_H_INCLUDED
#define SETTINGS_H_INCLUDED
#define _CRT_SECURE_NO_WARNINGS

#include <math.h>

#define APP_NAME "EVOC2D"
#define WINDOW_MODE 1//0 -fs, 1 -window fs, 2 -windowed
#define DEFAULT_SCRN_WIDTH 3840
#define DEFAULT_SCRN_HEIGHT 2160
#define INITIAL_CREATURE_COUNT 180
#define FOOD_COUNT 350
#define FOOD_RADIUS 6000
#define FOOD_COOLDOWN 10
#define VAO_POOL_VBO_CAPACITY 2000 //doesnt matter atm
#define VAO_POOL_EBO_CAPACITY 1000 // "" ""
#define COMPONENT_RADIUS 0.1f
#define MAX_CHILDREN 7
#define GROWTH_RADIUS 0.50f
#define GROWTH_ANGLE 2.0f * M_PI / MAX_CHILDREN
#define CREATURE_SPAWN_RADIUS 5000
#define STRUCTURAL_MUTATION_CHANCE 0.005
#define ABYSS_COUNT 1
#define MAX_SIGHT 3000
#define MAX_POPULATION 800
#define DRAW_INDEPENDENT true;
#define COMPONENT_INRADIUS COMPONENT_RADIUS * cosf(M_PI / MAX_CHILDREN)
#define MUTATE_CONNECTION_CHANCE 0.5f
#define MUTATE_GENE_CHANCE 0.5f
#define MUTATE_CONNECTION_STATE_CHANCE 0.2f
#define INITIAL_CREATURE_LIFE_SPAN 8
#endif
